### ISSUE TITLE
exponential restart ?

### ISSUE THREAD

**Issue by benoitc** [Pouriya-Jahanbakhsh/director#4]
It would be very interesting to have exponential restart until a max to not retry too fast.

**Comment by Pouriya-Jahanbakhsh** [comment]
Can you show a simple example? I really want to make it better. Thanks.

**Comment by Pouriya-Jahanbakhsh** [comment]
In every childspec you have a key called `state` with default value `undefined`. In every process crash Director will pass its state as an argument of its plan fun. You can save timestamp in state and define return value of plan fun (`stop`, `delete`, `wait`, `{restart, MilliSex}` and `restart`) based difference of current timestamp and last defined timestamp.
